### ISSUE TITLE
1.8.2+后dice插件无法在wine中正确加载

### ISSUE THREAD

**Issue by twfx1207** [iTXTech/mirai-native#51]
由于一些小问题，今天把wine docker里的mirai内核升级了一下（mirai-core-qqandroid-1.1.3 → 1.2.1），顺带把mirai-native升级到了1.8.6。
在旧版本（1.8.1）下dice插件可以正常加载，但是升级到新版以后就会报126错误。尝试降级以后发现此问题在1.8.2以上版本均会发生。
因为mirai内核升级，1.8.1版本已无法在新内核下正常加载，希望可以调查一下哪里出了问题。

**Comment by PeratX** [comment]
能否发一下docker配置

**Comment by twfx1207** [comment]
docker容器是Ubuntu18.04+wine 5.14，docker-compose如下：
```
services:
  mirai:
    image: msjpq/wine-vnc:bionic
    container_name: mirai
    ports:
      - 9000:8080
    environment:
      - LANG=zh_CN.UTF-8
      - LC_ALL=zh_CN.UTF-8
      - TZ=Asia/Shanghai
    volumes:
      - ./mirai:/root/Desktop/mirai
    restart: always
```
